-- MySQL Script generated by MySQL Workbench
-- 03/26/17 14:27:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teste
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `teste` ;

-- -----------------------------------------------------
-- Schema teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `teste` ;

-- -----------------------------------------------------
-- Table `teste`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `teste`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(150) NULL,
  `identificacao` VARCHAR(50) NULL,
  `email` VARCHAR(150) NULL,
  `data_cadastro` DATE NULL,
  `senha` TEXT NULL,
  `status` INT NULL,
  `nome_completo` VARCHAR(250) NULL,
  `tel` VARCHAR(45) NULL,
  `cel` VARCHAR(45) NULL,
  `logradouro` VARCHAR(250) NULL,
  `num_residencia` VARCHAR(45) NULL,
  `cidade` VARCHAR(250) NULL,
  `uf` VARCHAR(10) NULL,
  `bairro` VARCHAR(250) NULL,
  `cep` VARCHAR(10) NULL,
  `complemento` VARCHAR(250) NULL,
  `token` VARCHAR(250) NULL,
  `img_profile` VARCHAR(250) NULL,
  `outras_infos` VARCHAR(250) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste`.`grupos` ;

CREATE TABLE IF NOT EXISTS `teste`.`grupos` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `cod` VARCHAR(45) NULL,
  `descricao` VARCHAR(150) NULL,
  `data_criacao` DATE NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`usuarios_x_grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste`.`usuarios_x_grupos` ;

CREATE TABLE IF NOT EXISTS `teste`.`usuarios_x_grupos` (
  `id_usuario_x_grupo` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NULL,
  `fk_grupo` INT NULL,
  PRIMARY KEY (`id_usuario_x_grupo`),
  INDEX `fk_usuario_idx` (`fk_usuario` ASC),
  INDEX `fk_grupo_idx` (`fk_grupo` ASC),
  CONSTRAINT `fk_usuario_x5354435x`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `teste`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_x5354435x`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `teste`.`grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste`.`acessos` ;

CREATE TABLE IF NOT EXISTS `teste`.`acessos` (
  `id_acesso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `tipo` ENUM('VER_ED_REM','SIM_NAO') NULL,
  `cod` VARCHAR(45) NULL,
  PRIMARY KEY (`id_acesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`grupos_x_acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste`.`grupos_x_acessos` ;

CREATE TABLE IF NOT EXISTS `teste`.`grupos_x_acessos` (
  `id_grupo_x_acesso` INT NOT NULL AUTO_INCREMENT,
  `fk_grupo` INT NULL,
  `fk_acesso` INT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupo_x_acesso`),
  INDEX `fk_acesso_idx` (`fk_acesso` ASC),
  INDEX `fk_grupo_idx` (`fk_grupo` ASC),
  CONSTRAINT `fk_grupo_2x`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `teste`.`grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acesso_2x`
    FOREIGN KEY (`fk_acesso`)
    REFERENCES `teste`.`acessos` (`id_acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
